---
title: ""
header-includes:
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{graphicx}
  - \setlength{\parskip}{1em}
  - \usepackage{leading}
  - \leading{5pt}
output:
  pdf_document: 
    extra_dependencies: ["float","booktabs" ]
params:
  table: NA
  ggCharts: NA
  paramTable: NA
---

```{r intro, include=FALSE}

options(knitr.table.format = "latex")

defaultW <- getOption("warn") 
options(warn = -1)


```

## CovidU: Detailed Report ^[Contact: Gary King <king@harvard.edu>, Zagreb Mukerjee <zagrebmukerjee@fas.harvard.edu>] 

### Summary Report

```{r basicTable, echo = FALSE,comment=NA,background=NA}
  
params$paramTable$basicTable %>% kable(align = "lcr", row.names = FALSE, col.names = NULL, booktabs = TRUE, format = "latex") %>%
  kable_styling(latex_options = c("striped"), font_size = 8, position = "center")
```
**Testing and Costs**
```{r testTable, echo = FALSE,comment=NA,background=NA}
params$paramTable$testTable%>% kable(align = "lcr", row.names = FALSE, col.names = NULL, booktabs = TRUE, format = "latex") %>%
  kable_styling(latex_options = c("striped"), font_size = 8, position = "center")

```
**Population and Social**
```{r popsocTable, echo = FALSE,comment=NA,background=NA}
  
params$paramTable$popsocTable%>% kable(align = "lcr", row.names = FALSE, col.names = NULL, booktabs = TRUE, format = "latex") %>%
    kable_styling(latex_options = c("striped"), font_size = 8, position = "center")


```
**More Assumptions**
```{r extraTable, echo = FALSE,comment=NA,background=NA}
  
params$paramTable$extraTable%>% kable(align = "lcr", row.names = FALSE, col.names = NULL, booktabs = TRUE, format = "latex") %>%
    kable_styling(latex_options = c("striped"), font_size = 8, position = "center")


```
  

```{r charts, echo = FALSE, fig.height=4}
grid.arrange(params$ggCharts$trajectoryGGPlot, params$ggCharts$occupancyGGPlot, ncol = 2)
```



```{r end, include = FALSE}

options(warn = defaultW)

```